//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cessnas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Havalimani
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Havalimani()
        {
            this.Ucus = new HashSet<Ucu>();
            this.Ucus1 = new HashSet<Ucu>();
        }
    
        public int HavalimaniKod { get; set; }
        public string IATAKodu { get; set; }
        public string Ad { get; set; }
        public string Sehir { get; set; }
        public string Ulke { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ucu> Ucus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ucu> Ucus1 { get; set; }
    }
}
