//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cessnas
{
    using System;
    using System.Collections.Generic;
    
    public partial class HazirlikKontrol
    {
        public int TeknisyenKod { get; set; }
        public int UcakKod { get; set; }
        public int UcusKod { get; set; }
        public Nullable<System.DateTime> HazirlikZamani { get; set; }
        public string Notlar { get; set; }
    
        public virtual Teknisyen Teknisyen { get; set; }
        public virtual Ucak Ucak { get; set; }
        public virtual Ucu Ucu { get; set; }
    }
}
