//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cessnas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Koltuk
    {
        public int UcakKod { get; set; }
        public string KoltukNo { get; set; }
        public string KoltukTipi { get; set; }
        public Nullable<int> DizMesafesi { get; set; }
    
        public virtual Ucak Ucak { get; set; }
    }
}
