//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cessnas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cessnasEntities : DbContext
    {
        public cessnasEntities()
            : base("name=cessnasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Havalimani> Havalimanis { get; set; }
        public virtual DbSet<HazirlikKontrol> HazirlikKontrols { get; set; }
        public virtual DbSet<Hoste> Hostes { get; set; }
        public virtual DbSet<Koltuk> Koltuks { get; set; }
        public virtual DbSet<Pilot> Pilots { get; set; }
        public virtual DbSet<Rezervasyon> Rezervasyons { get; set; }
        public virtual DbSet<Teknisyen> Teknisyens { get; set; }
        public virtual DbSet<Ucak> Ucaks { get; set; }
        public virtual DbSet<Ucu> Ucus { get; set; }
        public virtual DbSet<Yakit> Yakits { get; set; }
        public virtual DbSet<Yolcu> Yolcus { get; set; }
    }
}
