//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cessnas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervasyon
    {
        public int RezervasyonKod { get; set; }
        public int YolcuKod { get; set; }
        public int UcusKod { get; set; }
        public Nullable<System.DateTime> RezervasyonZamani { get; set; }
        public string Sinif { get; set; }
        public string OdemeDurumu { get; set; }
        public string KoltukNo { get; set; }
    
        public virtual Ucu Ucu { get; set; }
        public virtual Yolcu Yolcu { get; set; }
    }
}
