//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cessnas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ucak
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ucak()
        {
            this.HazirlikKontrols = new HashSet<HazirlikKontrol>();
            this.Koltuks = new HashSet<Koltuk>();
            this.Ucus = new HashSet<Ucu>();
        }
    
        public int UcakKod { get; set; }
        public string KuyrukNo { get; set; }
        public string Model { get; set; }
        public string Uretici { get; set; }
        public Nullable<int> Kapasite { get; set; }
        public Nullable<int> UretimYili { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HazirlikKontrol> HazirlikKontrols { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Koltuk> Koltuks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ucu> Ucus { get; set; }
    }
}
