//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cessnas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ucu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ucu()
        {
            this.HazirlikKontrols = new HashSet<HazirlikKontrol>();
            this.Rezervasyons = new HashSet<Rezervasyon>();
            this.Yakits = new HashSet<Yakit>();
            this.Hostes = new HashSet<Hoste>();
        }
    
        public int UcusKod { get; set; }
        public string UcusNo { get; set; }
        public Nullable<System.DateTime> KalkisZamani { get; set; }
        public Nullable<System.DateTime> VarisZamani { get; set; }
        public string Durum { get; set; }
        public Nullable<int> UcakKod { get; set; }
        public Nullable<int> PilotKod { get; set; }
        public Nullable<int> KalkisHavalimaniKod { get; set; }
        public Nullable<int> VarisHavalimaniKod { get; set; }
    
        public virtual Havalimani Havalimani { get; set; }
        public virtual Havalimani Havalimani1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HazirlikKontrol> HazirlikKontrols { get; set; }
        public virtual Pilot Pilot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervasyon> Rezervasyons { get; set; }
        public virtual Ucak Ucak { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yakit> Yakits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hoste> Hostes { get; set; }
    }
}
