//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cessnas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yakit
    {
        public int YakitKod { get; set; }
        public int UcusKod { get; set; }
        public int TeknisyenKod { get; set; }
        public Nullable<double> MiktarLitre { get; set; }
        public Nullable<double> BirimFiyat { get; set; }
        public double ToplamTutar { get; set; }
    
        public virtual Teknisyen Teknisyen { get; set; }
        public virtual Ucu Ucu { get; set; }
    }
}
